### ISSUE TITLE
Setting targetSdkVersion 24, app crashes.

### ISSUE THREAD

**Issue by shivamsingh** [sourab-sharma/TouchToRecord#28]
App works perfectly for targetSdkVersion 19 but when we change it to 24 it crashes.

Exception:

> Process: com.sourab.videorecorder, PID: 11480
>                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:309)
>                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                               at java.lang.Thread.run(Thread.java:818)
>                                                                            Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec
>                                                                               at java.lang.Class.classForName(Native Method)
>                                                                               at java.lang.Class.forName(Class.java:324)
>                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:413)
>                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:381)
>                                                                               at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
>                                                                               at com.sourab.videorecorder.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:182)
>                                                                               at com.sourab.videorecorder.FFmpegRecorderActivity.initVideoRecorder(FFmpegRecorderActivity.java:404)
>                                                                               at com.sourab.videorecorder.FFmpegRecorderActivity.access$1700(FFmpegRecorderActivity.java:68)
>                                                                               at com.sourab.videorecorder.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:314)
>                                                                               at com.sourab.videorecorder.FFmpegRecorderActivity$2.doInBackground(FFmpegRecorderActivity.java:308)
>                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)

**Comment by aksharora** [comment]
@shivamsingh do you fix this issue? if you fixed please share solution with me.

**Comment by ArslanKathia** [comment]
@shivamsingh i am also facing this issue. if you fixed this issue please share solution with me...Thanks in advance
